// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfettiController from "./confetti_controller"
application.register("confetti", ConfettiController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LeadSwipeController from "./lead_swipe_controller"
application.register("lead-swipe", LeadSwipeController)

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)